### ISSUE TITLE
Luigi's Mansion Branch Roadmap 

### ISSUE THREAD

**Issue by BootsinSoots** [BootsinSoots/Archipelago#1]
### What feature would you like to see?

# Luigi's Mansion Archipelago Roadmap

### World Files
- [x] Basic file structure
- [ ] Create Items for progressive huge plant 
- [x] Successful Generation with any option combination
- [x] Use generate output to supply client
- [ ] Write Test Suite
### Feature: No Vacuum Start
- [x] Create logic to force a local key within first checks
- [x] Make Parlor Key Drop an accessible check
- [x] Add check to First E. Gadd cutscene
### Feature: Enemizer
- [x] Define ghost types by LMWorld instance
- [x] Define methods to randomize Ghost types in appropriate rooms
- [x] Create Logic rules for locations and entrances that force you to beat ghosts to pass
- [x] Push information to client for modification
### Feature: Boosanity
- [ ] Figure out how to add drops to Boos - Perhaps make locations send to server every time?
- [ ] Create logic for high HP Boos
### Feature: Poltergust Hunt 
 - [ ] Force Luigi to start with all keys
 - [ ] Fill all further locations with filler and other unique items and 1 instance of the Poltergust 3000
 - [ ] Write logical requirement for vacuum to appropriate locations
### Feature: Rank Requirement
 - [x] Create options and logical rules
 - [x] Create money determination to be added during generation to ensure enough money is created
### Game modification
- [x] Recreate methods in keyinfo that work for any kind of item
- [x] Locate and modify code for Mario's Star event in observatory
- [ ] Locate and modify code for Huge Plant to add as potential location without hardlocks
- [ ] Locate "missing" furniture pieces to see if they can be added as locations
- [ ] Add a trigger/observer on Breaker to let the player switch to blackout and back at will
- [x] Automate JMP modification
- [x] Automate DOL modification
### Communication
 - [ ] Ensure communication with server works
 - [ ] Code outbound from game hooks
 - [ ] Code inbound game hooks
 - [ ] Handle sending of too many copies of items
### Portrait Ghosts
 - [ ] Figure out where and how to get an item from capturing a boss ghost. Observer that spawns item of boss chest?
 - [ ] Twins listed in characterinfo may not be ones that actually are caught, need to test to ensure they can drop items 
 - [ ] Jarvis only has entries on generatorinfo for modification
 - [ ] Change Portrait Heart Text
### Feature: No Vacuum Start
- [ ] Ensure initial E. Gadd cutscene functions appropriately if accessed later
- [ ] Make Parlor Key Drop an accessible check
- [ ] Add check to First E. Gadd cutscene
- [ ] Toggle Luigi model to No Vacuum
### Feature: Enemizer
 - [x] Make changes to correct tables to spawn waves with correct ghosts
### Feature: Boosanity
 - [ ] Figure out how to makes Boos drop items 
 - [ ] Alternately, hook into the Boo catch to receive the check but not increase counter
### Feature: Poltergust Hunt 
 - [ ] Give all keys to Luigi at Game start
 - [ ] Create enough filler to fill locations after unique items given
### Feature: Speedy Spirits
 - [ ] Force Speedy Spirits to respawn if not caught
 - [ ] Force Speedy Spirits to drop an item when caught
### Feature: Toadsanity
 - [ ] Find a way to notify server of talking to the toads - hook into first conversation with them?
### Feature: Rank Requirement
 - [ ] Find/write a way to check what rank is received at end of game to mark for release
